In [11]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator, SimpleImputer


In [5]:
df = pd.read_csv('D:/MLworkspace/excelFiles/titanic_toy.csv',usecols=['Age','Fare','Survived'])

In [6]:
df

Age     Fare  Survived
0    22.0   7.2500         0
1    38.0  71.2833         1
2    26.0   7.9250         1
3    35.0  53.1000         1
4    35.0   8.0500         0
..    ...      ...       ...
886  27.0  13.0000         0
887  19.0  30.0000         1
888   NaN  23.4500         0
889  26.0      NaN         1
890  32.0   7.7500         0

[891 rows x 3 columns]

In [8]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [14]:
si = SimpleImputer() #created class
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.transform(x_test)


In [15]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [16]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred = clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6033519553072626

In [27]:
# Now, with missing Indicator
#did't get much from here

mi = MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [28]:
mi.features_

array([0, 1], dtype=int64)

In [19]:
x_train_missing = mi.transform(x_train)

In [20]:
x_train_missing

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [ True, False],
       [ True, False]])

In [24]:
x_test_missing = mi.transform(x_test)

In [25]:
x_test_missing

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [Fal

In [ ]:
x_train['Age_NA'] = x_train_missing

In [30]:
x_test

Age     Fare
707  42.0  26.2875
37   21.0   8.0500
615  24.0  65.0000
169  28.0  56.4958
68   17.0   7.9250
..    ...      ...
89   24.0   8.0500
80   22.0   9.0000
846   NaN  69.5500
870  26.0   7.8958
251  29.0      NaN

[179 rows x 2 columns]

In [ ]:
x_test['Age_NA'] = x_test_missing

In [32]:
x_train

Age      Fare
30   40.0   27.7208
10    4.0   16.7000
873  47.0    9.0000
182   9.0   31.3875
876  20.0    9.8458
..    ...       ...
534  30.0    8.6625
584   NaN    8.7125
493  71.0   49.5042
527   NaN  221.7792
168   NaN   25.9250

[712 rows x 2 columns]

In [34]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [35]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2,y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6033519553072626

In [36]:
si = SimpleImputer(add_indicator=True)

In [37]:
x_train = si.fit_transform(x_train)

In [38]:
x_test = si.transform(x_test)

In [39]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2,y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6033519553072626

In [ ]:
#from missing indicator, not clear much,
# PENDING !!!